sudo: false

language: python

python:
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOXENV=py27-django18,py33-django18
  - TOXENV=py27-django111,py35-django111

install:
  - pip install tox pip wheel codecov -U

script:
    - tox

after_success:
  - codecov -e TOX_ENV

branches:
  only:
    - master
